{% set name = "tiledb-bioimg" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tiledb-bioimg-{{ version }}.tar.gz
  sha256: 7df0c634df7eafec6aed8df1f9ab742af0b4fd8b1adbc1556ccc66253d58c377
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - pyeditdistance
    - python >=3.7
    - tiledb >=0.19
    - tqdm
    - scikit-image

test:
  imports:
    - tiledb
  commands:
    - pip list
    # - pip check  # fails due to tiledb not being found
  requires:
    - pip

about:
  home: https://pypi.org/project/tiledb-bioimg
  summary: Package supports all bio-imaging functionality provided by TileDB
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/TileDB-Inc/TileDB-Bioimaging

extra:
  recipe-maintainers:
    - goanpeca
