{% set name = "tiledb-bioimg" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 829344e68dce0ff4453bd28ac00a49d26bd7f161eaba0684e0086768ec3778de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - pyeditdistance
    - python >=3.7
    - tifffile
    - tiledb-py >=0.19
    - tqdm
    - scikit-image
    # Optional dependencies
    - imagecodecs
    - jsonpickle
    - ome-zarr
    - openslide-python
    # - tiledb-cloud

test:
  imports:
    - tiledb
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tiledb-bioimg
  summary: Package supports all bio-imaging functionality provided by TileDB
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/TileDB-Inc/TileDB-Bioimaging

extra:
  recipe-maintainers:
    - goanpeca
